spring:
  datasource:
    url: jdbc:mysql://120.25.152.218:3306/jinqianl_dev?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
#  rabbitmq:
#    host: 10.204.119.126
#    port: 5672
#    username: springcloud
#    password: 123456
#    virtual-host: vacp
    
mybatis:
  type-aliases-package: com.jinqianl
  mapper-locations: classpath:com/jinqianl/*.xml
  
logging:
  file: /logs/jinqianl.log
  level:
    feign: DEBUG
    com: 
      jinqianl: DEBUG

customize: 
  auth-address: localhost:8090/yundao
  access-key: 95a9b4b048dc008aaff16b6f83adb5e1  
  script-path: /root/vacp/scripts